# Generated by Django 3.2.5 on 2021-10-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, default='/default.png', null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
