# Generated by Django 3.2.5 on 2021-10-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=2000, null=True, unique=True)),
                ('address', models.TextField(blank=True, max_length=2000, null=True)),
                ('telephone', models.TextField(blank=True, max_length=2000, null=True)),
                ('contact_person', models.TextField(blank=True, max_length=2000, null=True)),
                ('cp_mobile', models.TextField(blank=True, max_length=2000, null=True)),
                ('priority', models.TextField(blank=True, max_length=2000, null=True)),
                ('Remark', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
