# Generated by Django 3.2.5 on 2021-10-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership_plan', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=2000, null=True)),
                ('email', models.EmailField(blank=True, max_length=2000, null=True, unique=True)),
                ('logo', models.TextField(default='/media/default.png', max_length=2000, null=True)),
                ('phone', models.TextField(blank=True, max_length=2000, null=True)),
                ('fbLink', models.TextField(blank=True, max_length=2000, null=True)),
                ('type', models.TextField(blank=True, max_length=2000, null=True)),
                ('status', models.TextField(default='Active', max_length=2000, null=True)),
                ('primary_color', models.TextField(default='#a177f7', max_length=2000, null=True)),
                ('currency', models.TextField(default='MMK', max_length=2000, null=True)),
                ('address', models.TextField(default='', max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(default='Active', max_length=2000, null=True)),
                ('exp_date', models.DateTimeField(null=True)),
                ('free_trail_exp_date', models.DateTimeField(null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='membership_plan.membershipplan')),
                ('store', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
