# Generated by Django 3.2.5 on 2021-10-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=2000, null=True)),
                ('address', models.TextField(blank=True, max_length=2000, null=True)),
                ('telephone', models.TextField(blank=True, max_length=2000, null=True)),
                ('website', models.TextField(blank=True, max_length=2000, null=True)),
                ('facebook_page', models.TextField(blank=True, max_length=2000, null=True)),
                ('contact_person', models.TextField(blank=True, max_length=2000, null=True)),
                ('cp_mobile', models.TextField(blank=True, max_length=2000, null=True)),
                ('cp_mail', models.EmailField(blank=True, max_length=2000, null=True, unique=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccountInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=2000, null=True)),
                ('account_number', models.TextField(max_length=2000, null=True)),
                ('account_holder_name', models.TextField(max_length=2000, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='supplier.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
