# Generated by Django 3.2.5 on 2021-10-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('customer', '0002_customer_store'),
        ('delivery', '0002_delivery_store'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='store.store'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sale.sale'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', to='store.store'),
        ),
        migrations.AddField(
            model_name='saleaddress',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='sale.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='store.store'),
        ),
    ]
