# Generated by Django 3.2.5 on 2022-01-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_store'),
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='link',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='sale',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='money_price',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='percentage',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
