# Generated by Django 3.2.5 on 2022-01-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_balance'),
        ('order', '0006_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.TextField(blank=True, max_length=2000, null=True)),
                ('app', models.TextField(default='Pin Dou Dou', max_length=2000, null=True)),
                ('note', models.TextField(blank=True, default='', max_length=2000, null=True)),
                ('code', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_arrived', models.BooleanField(default=False)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_codes', to='store.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_arrived', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='order.ordercodes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
