# Generated by Django 3.2.5 on 2022-01-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_code_ordercodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercodes',
            name='store',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='app',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='money_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='OrderCodes',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
