# Generated by Django 3.2.5 on 2022-01-17 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='supplier',
            new_name='cargo',
        ),
    ]
